@startuml AppLogic
state "AppLogic State" as Eggsploration_AppLogic_State {
  state "InMainMenu" as Eggsploration_AppLogic_State_InMainMenu
  state "InGame" as Eggsploration_AppLogic_State_InGame
  state "ClosingApplication" as Eggsploration_AppLogic_State_ClosingApplication
}

Eggsploration_AppLogic_State_InMainMenu --> Eggsploration_AppLogic_State_ClosingApplication : QuitClick
Eggsploration_AppLogic_State_InMainMenu --> Eggsploration_AppLogic_State_InGame : NewGameClick

Eggsploration_AppLogic_State_ClosingApplication : OnEnter → QuitApp
Eggsploration_AppLogic_State_InGame : OnEnter → StartNewGame

[*] --> Eggsploration_AppLogic_State_InMainMenu
@enduml